declare module "*.png";
declare module "*.svg";
declare module "*.jpg";
declare module "*.gif";
declare module "reactjs-localstorage";
declare module "react-fullscreen-loading";
declare module "country-list-json";
declare module "react-facebook-login";
declare module "react-facebook-login/dist/facebook-login-render-props";
declare module "react-pdf";
declare module "query-string";
declare module "react-google-recaptcha";
declare module "react-xml-viewer";
declare module "quill";
// declare module 'react-copy-to-clipboard';
// declare module 'file-saver';
// declare module 'react-bootstrap-image-cropper';
